import {
  ShoppingBag, Home, Utensils, Car, Gamepad, ShoppingCart, Heart, GraduationCap, 
  DollarSign, Briefcase, Gift, Banknote, CreditCard, PiggyBank, Coins, TrendingUp,
  FileText, Percent, Landmark, Wallet, Sofa, Bed, Bath, Tv, Lightbulb, 
  Brush, Hammer, Wrench, Armchair, House, Beef, Cake, Coffee, Wine, Beer, 
  Carrot, Cookie, Drumstick, Fuel, Bus, Train, Plane, Bike, Ship, 
  Film, Music, Ticket, Theater, Dice1 as Dice, Book, Headphones, Guitar, Trophy, Palette, 
  Stethoscope, Pill, Building, Building2, Eye, Dumbbell, Footprints, Cross, Brain,
  Shirt, Gem, Scissors, SprayCan, Glasses, Baby, PawPrint, Laptop, Smartphone, 
  Camera, Printer, Wifi, Monitor, Keyboard, HardDrive, MessageSquare
} from "lucide-react";

// Define the type for iconMap
export interface IconMap {
  [key: string]: JSX.Element;
}

// Map of icon values to Lucide components
export const iconMap: IconMap = {
  "fas fa-shopping-bag": <ShoppingBag size={20} />,
  "fas fa-home": <Home size={20} />,
  "fas fa-utensils": <Utensils size={20} />,
  "fas fa-car": <Car size={20} />,
  "fas fa-gamepad": <Gamepad size={20} />,
  "fas fa-shopping-cart": <ShoppingCart size={20} />,
  "fas fa-heartbeat": <Heart size={20} />,
  "fas fa-graduation-cap": <GraduationCap size={20} />,
  "fas fa-dollar-sign": <DollarSign size={20} />,
  "fas fa-briefcase": <Briefcase size={20} />,
  "fas fa-gift": <Gift size={20} />,
  "fas fa-money-bill": <Banknote size={20} />,
  "fas fa-credit-card": <CreditCard size={20} />,
  "fas fa-piggy-bank": <PiggyBank size={20} />,
  "fas fa-coins": <Coins size={20} />,
  "fas fa-chart-line": <TrendingUp size={20} />,
  "fas fa-hand-holding-usd": <Coins size={20} />,
  "fas fa-file-invoice-dollar": <FileText size={20} />,
  "fas fa-donate": <Coins size={20} />,
  "fas fa-percentage": <Percent size={20} />,
  "fas fa-landmark": <Landmark size={20} />,
  "fas fa-wallet": <Wallet size={20} />,
  "fas fa-couch": <Sofa size={20} />,
  "fas fa-bed": <Bed size={20} />,
  "fas fa-bath": <Bath size={20} />,
  "fas fa-tv": <Tv size={20} />,
  "fas fa-lightbulb": <Lightbulb size={20} />,
  "fas fa-broom": <Brush size={20} />,
  "fas fa-tools": <Wrench size={20} />,
  "fas fa-hammer": <Hammer size={20} />,
  "fas fa-chair": <Armchair size={20} />,
  "fas fa-house-user": <House size={20} />,
  "fas fa-hamburger": <Beef size={20} />,
  "fas fa-pizza-slice": <Cake size={20} />,
  "fas fa-coffee": <Coffee size={20} />,
  "fas fa-cocktail": <Wine size={20} />,
  "fas fa-wine-glass-alt": <Wine size={20} />,
  "fas fa-beer": <Beer size={20} />,
  "fas fa-ice-cream": <Cake size={20} />,
  "fas fa-carrot": <Carrot size={20} />,
  "fas fa-cookie": <Cookie size={20} />,
  "fas fa-drumstick-bite": <Drumstick size={20} />,
  "fas fa-car-alt": <Car size={20} />,
  "fas fa-gas-pump": <Fuel size={20} />,
  "fas fa-oil-can": <Fuel size={20} />,
  "fas fa-bus": <Bus size={20} />,
  "fas fa-train": <Train size={20} />,
  "fas fa-subway": <Train size={20} />,
  "fas fa-taxi": <Car size={20} />,
  "fas fa-bicycle": <Bike size={20} />,
  "fas fa-plane": <Plane size={20} />,
  "fas fa-ship": <Ship size={20} />,
  "fas fa-film": <Film size={20} />,
  "fas fa-music": <Music size={20} />,
  "fas fa-ticket-alt": <Ticket size={20} />,
  "fas fa-theater-masks": <Theater size={20} />,
  "fas fa-dice": <Dice size={20} />,
  "fas fa-book": <Book size={20} />,
  "fas fa-headphones": <Headphones size={20} />,
  "fas fa-guitar": <Guitar size={20} />,
  "fas fa-bowling-ball": <Trophy size={20} />,
  "fas fa-palette": <Palette size={20} />,
  "fas fa-stethoscope": <Stethoscope size={20} />,
  "fas fa-pills": <Pill size={20} />,
  "fas fa-hospital": <Building size={20} />,
  "fas fa-tooth": <Building2 size={20} />,
  "fas fa-eye": <Eye size={20} />,
  "fas fa-dumbbell": <Dumbbell size={20} />,
  "fas fa-running": <Footprints size={20} />,
  "fas fa-spa": <Brush size={20} />,
  "fas fa-first-aid": <Cross size={20} />,
  "fas fa-brain": <Brain size={20} />,
  "fas fa-tshirt": <Shirt size={20} />,
  "fas fa-shoe-prints": <Footprints size={20} />,
  "fas fa-gem": <Gem size={20} />,
  "fas fa-cut": <Scissors size={20} />,
  "fas fa-spray-can": <SprayCan size={20} />,
  "fas fa-glasses": <Glasses size={20} />,
  "fas fa-baby": <Baby size={20} />,
  "fas fa-paw": <PawPrint size={20} />,
  "fas fa-laptop": <Laptop size={20} />,
  "fas fa-mobile-alt": <Smartphone size={20} />,
  "fas fa-camera": <Camera size={20} />,
  "fas fa-print": <Printer size={20} />,
  "fas fa-wifi": <Wifi size={20} />,
  "fas fa-keyboard": <Keyboard size={20} />,
  "fas fa-hdd": <HardDrive size={20} />,
  "fas fa-comments-dollar": <MessageSquare size={20} />,
  "fas fa-money-check-alt": <FileText size={20} />,
};

export const getIconComponent = (iconValue: string) => {
  return iconMap[iconValue] || <ShoppingBag size={20} />;
}; 